version: '2'
services:
  webapp:
    build: webapp/
    ports:
    - "80:8080"
    - "8080:8080"
    links:
    - db
    - logstash
    networks:
    - default
    # entrypoint: sleep
    # command:
    # - infinity
  db:
    build: mysql/
    links:
    - logstash
    volumes: 
    - dbdata:/var/lib/mysql:rw
    networks:
    - default
  elasticsearch:
    image: elasticsearch:latest
    command: elasticsearch -Des.network.host=0.0.0.0
    ports:
    - "9200:9200"
    - "9300:9300"
    networks:
    - default
  logstash:
    image: logstash:latest
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
    - ./logstash/config:/etc/logstash/conf.d
    ports:
    - "5000:5000"
    links:
    - elasticsearch
    networks:
    - default
  kibana:
    build: kibana/
    volumes:
    - ./kibana/config/:/opt/kibana/config/
    ports:
    - "5601:5601"
    links:
    - elasticsearch
    networks:
    - default
networks:
  default:
    driver: bridge
volumes:
  dbdata:
    driver: local